//! Clickable scrollbar with mouse support.
//!
//! This module provides a clickable scrollbar widget that extends ratatui's
//! `Scrollbar` with mouse interaction support including clicking, dragging, and
//! scroll wheel events.
//!
//! # Components
//!
//! - [`ClickableScrollbar`] - The widget component that renders the scrollbar
//! - [`ClickableScrollbarState`] - State management for scroll position and mouse interactions
//! - [`ScrollbarEvent`] - Events generated by scrollbar interactions
//!
//! # Example
//!
//! ```rust,no_run
//! use ratatui::layout::Rect;
//! use ratatui::widgets::ScrollbarOrientation;
//! use ratatui_toolkit::{ClickableScrollbar, ClickableScrollbarState, ClickableScrollbarStateScrollExt};
//!
//! let scrollbar = ClickableScrollbar::vertical();
//! let mut state = ClickableScrollbarState::new()
//!     .set_content(100, 10)
//!     .position(5);
//! ```

pub mod constructors;
pub mod methods;
pub mod traits;

pub use methods::*;

use ratatui::layout::Rect;
use ratatui::widgets::Scrollbar;
use ratatui::widgets::ScrollbarOrientation;

/// Clickable scrollbar widget.
///
/// This wraps ratatui's `Scrollbar` but adds mouse interaction support for
/// clicking, dragging, and scroll wheel events. The widget renders a standard
/// scrollbar but manages state to handle mouse interactions and generate
/// scroll events.
///
/// # Type Parameters
///
/// * `'a` - Lifetime of the scrollbar symbols
///
/// # Example
///
/// ```rust
/// use ratatui_toolkit::ClickableScrollbar;
/// use ratatui::widgets::ScrollbarOrientation;
///
/// let scrollbar = ClickableScrollbar::vertical();
/// ```
#[derive(Debug, Default, Clone)]
pub struct ClickableScrollbar<'a> {
    /// Orientation of the scrollbar (vertical or horizontal)
    orientation: ScrollbarOrientation,
    /// The underlying ratatui scrollbar widget
    scrollbar: Scrollbar<'a>,
}

/// State for the clickable scrollbar.
///
/// This manages scrolling position, content bounds, and handles mouse interactions
/// including clicks, drags, and scroll wheel events. The state is mutable and
/// tracks the current scroll position within the content.
///
/// # Fields
///
/// - `area` - The area where the scrollbar is rendered (set during rendering)
/// - `orientation` - The scrollbar orientation (vertical or horizontal)
/// - `offset` - Current scroll offset (position in content, 0 = top/left)
/// - `page_len` - Length of the visible content area (viewport size)
/// - `max_offset` - Maximum scroll offset (content_length - page_len)
/// - `scroll_by` - Number of units to scroll per wheel event (None = auto)
/// - `drag_active` - Whether a mouse drag is currently active (private)
///
/// # Example
///
/// ```rust
/// use ratatui_toolkit::{ClickableScrollbarState, ClickableScrollbarStateScrollExt};
///
/// let mut state = ClickableScrollbarState::new()
///     .set_content(100, 10)  // 100 total items, 10 visible
///     .position(25);          // Scroll to position 25
/// ```
#[derive(Debug, Clone)]
pub struct ClickableScrollbarState {
    /// Area where scrollbar is rendered (set during `render` call)
    pub area: Rect,
    /// Orientation of scrollbar (vertical or horizontal)
    pub orientation: ScrollbarOrientation,
    /// Current scroll offset (position in content, 0 = top/left)
    pub offset: usize,
    /// Length of visible content area (viewport size in lines/columns)
    pub page_len: usize,
    /// Maximum scroll offset (content_length - page_len, or 0 if content fits)
    pub max_offset: usize,
    /// How many lines/columns to scroll per wheel event (None = auto-calculate)
    pub scroll_by: Option<usize>,
    /// Track if mouse drag is active (private field)
    drag_active: bool,
}

/// Result of handling mouse events on the scrollbar.
///
/// Represents the result of processing a mouse event on the scrollbar.
/// Events are returned from [`ClickableScrollbarState::handle_mouse_event`]
/// and indicate what action should be taken by the application.
///
/// # Variants
///
/// - [`None`] - No event or event not handled (e.g., mouse outside scrollbar area)
/// - [`Up(n)`] - Scroll up by n units (generated by scroll wheel up or drag up)
/// - [`Down(n)`] - Scroll down by n units (generated by scroll wheel down or drag down)
/// - [`Position(n)`] - Jump to absolute position n (generated by click or drag)
///
/// # Example
///
/// ```rust,no_run
/// use ratatui_toolkit::{ClickableScrollbarState, ClickableScrollbarStateScrollExt, ClickableScrollbarStateMouseExt, ScrollbarEvent};
/// use crossterm::event::MouseEvent;
///
/// let mut state = ClickableScrollbarState::new().set_content(100, 10);
/// // In real code, you'd get a MouseEvent from crossterm::event::read()
/// // match state.handle_mouse_event(&event) {
/// //     ScrollbarEvent::Up(n) => { /* scroll up by n */ }
/// //     ScrollbarEvent::Down(n) => { /* scroll down by n */ }
/// //     ScrollbarEvent::Position(pos) => { /* jump to position */ }
/// //     ScrollbarEvent::None => {}
/// // }
/// ```
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ScrollbarEvent {
    /// No event or event not handled.
    ///
    /// Returned when the mouse event is outside the scrollbar area or
    /// is not relevant to scrolling (e.g., right-click).
    None,

    /// Scroll up by N units.
    ///
    /// Generated by mouse wheel up events. The value N is the scroll increment,
    /// which is either the configured `scroll_by` value or auto-calculated as
    /// `page_len / 10` (minimum 1).
    Up(usize),

    /// Scroll down by N units.
    ///
    /// Generated by mouse wheel down events. The value N is the scroll increment,
    /// which is either the configured `scroll_by` value or auto-calculated as
    /// `page_len / 10` (minimum 1).
    Down(usize),

    /// Jump to absolute position.
    ///
    /// Generated by clicking on the scrollbar track or dragging the thumb.
    /// The position is an offset into the content (0 to max_offset).
    Position(usize),
}
